## <B>Week 09</B>

### ***Pandas***

<img src='img1.jpeg'>

### <u>***Pandas Series***</u>

In [6]:
import pandas as pd
ages = pd.Series([22, 38, 23, 67, 54])
print(ages)
print(type(ages))

0    22
1    38
2    23
3    67
4    54
dtype: int64
<class 'pandas.Series'>

Default 0,1,2,etc... are indexes.

In [ ]:
import pandas as pd
ages = pd.Series([22, 38, 23, 67, 54], index=['Bob', 'John', 'Sunny', 'Kasun', 'Nimal'])
print(ages)
print(type(ages))

Bob      22
John     38
Sunny    23
Kasun    67
Nimal    54
dtype: int64
<class 'pandas.Series'>

### <u>***Pandas Series Indexing***</u>

In [26]:
import pandas as pd
ages = pd.Series([22, 38, 23, 67, 54], index=['Bob', 'John', 'Sunny', 'Kasun', 'Nimal'])

print(ages.loc['Bob'])
print(ages.iloc[0])

22
22

Lets assume we haven't indexed

In [11]:
import pandas as pd
ages = pd.Series([22, 38, 23, 67, 54])
print(ages.loc[0])
###################################
print(ages.shape)

22
(5,)

### <u>***Pandas DataFrame***</u>

In [13]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, 28, 41],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo'],
                   'score': [0.81, 0.44, 0.92, 0.62]
                   })
print(df)
print(type(df))

   age     city  score
0   22  Colombo   0.81
1   35    Kandy   0.44
2   28    Galle   0.92
3   41  Colombo   0.62
<class 'pandas.DataFrame'>

We can import a excel datasheet and convert into a Pandas DataFrame and process it.

In [27]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, 28, 41],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo'],
                   'score': [0.81, 0.44, 0.92, 0.62]
                   })
print(df['city'].loc[2])
print(df.city[2])
print(df.loc[2, 'city'])
print(df.city.loc[2])
###### index based accessing #######
print(df.iloc[2,1]) 
##################################
print(df.shape)
print(df.dtypes)

Galle
Galle
Galle
Galle
Galle
(4, 3)
age        int64
city         str
score    float64
dtype: object

In [31]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, '28', 41],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo'],
                   'score': [0.81, 0.44, 0.92, 0.62]
                   })

print(df.dtypes)

age       object
city         str
score    float64
dtype: object

If there are mixed type in a Feature dtype is shown as a <b style='color:red'>object</b>

In [38]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, 28, 41, 52, 45, 72],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kalutara', 'Panadura', 'Gampaha'],
                   'score': [0.81, 0.44, 0.92, 0.62, 0.43, 0.95, 0.13]
                   })
print(df.head())
print(df.tail(2))

   age      city  score
0   22   Colombo   0.81
1   35     Kandy   0.44
2   28     Galle   0.92
3   41   Colombo   0.62
4   52  Kalutara   0.43
   age      city  score
5   45  Panadura   0.95
6   72   Gampaha   0.13

By Default head(),tail() gives first/last 5 rows.

In [40]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, 28, 41, 52, 45, 72],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kalutara', 'Panadura', 'Gampaha'],
                   'score': [0.81, 0.44, 0.92, 0.62, 0.43, 0.95, 0.13]
                   })
print(df.columns)
print(type(df.columns))

Index(['age', 'city', 'score'], dtype='str')
<class 'pandas.Index'>

In [42]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, 28, 41, 52, 45, 72],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kalutara', 'Panadura', 'Gampaha'],
                   'score': [0.81, 0.44, 0.92, 0.62, 0.43, 0.95, 0.13]
                   })
print(list(df.columns))

['age', 'city', 'score']

In [50]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, 28, 41, 52, 45, 72],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kalutara', 'Panadura', 'Gampaha'],
                   'score': [0.81, 0.44, 0.92, None, 0.43, 0.95, 0.13]
                   })
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     7 non-null      int64
 1   city    7 non-null      str
 2   score   6 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 300.0 bytes
None

In [51]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, 28, 41, 52, 45, 72],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kalutara', 'Panadura', 'Gampaha'],
                   'score': [0.81, 0.44, 0.92, None, 0.43, 0.95, 0.13]
                   })
print(df.describe())

             age     score
count   7.000000  6.000000
mean   42.142857  0.613333
std    16.607514  0.329646
min    22.000000  0.130000
25%    31.500000  0.432500
50%    41.000000  0.625000
75%    48.500000  0.892500
max    72.000000  0.950000

### <u>***<div style='padding:10px'>Reading .csv</div>***</u>

In [55]:
df = pd.read_csv('customers_tiny.csv')
print(df)
print(df.info())
print(df.describe())

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle    NaN          1
3  41.0  Colombo   0.67          1
4   NaN    Kandy   0.55          0
5  33.0    Galle   0.90          1
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        5 non-null      float64
 1   city       6 non-null      str
 2   score      5 non-null      float64
 3   purchased  6 non-null      int64
dtypes: float64(2), int64(1), str(1)
memory usage: 324.0 bytes
None
             age     score  purchased
count   5.000000  5.000000   6.000000
mean   31.800000  0.674000   0.666667
std     7.190271  0.186896   0.516398
min    22.000000  0.440000   0.000000
25%    28.000000  0.550000   0.250000
50%    33.000000  0.670000   1.000000
75%    35.000000  0.810000   1.000000
max    41.000000  0.900000   1.000000

In [76]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
print(df.loc[1:3,'city':'score'])
print(df.iloc[1:4,1:3])
print(df.iloc[range(1,4),1:3])

      city  score
1    Kandy   0.44
2    Galle    NaN
3  Colombo   0.67
      city  score
1    Kandy   0.44
2    Galle    NaN
3  Colombo   0.67
      city  score
1    Kandy   0.44
2    Galle    NaN
3  Colombo   0.67

<b style='color:blue'>loc</b> is label based and <b style='color:blue'>iloc</b> is based on indexes.

In [78]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
print(df['score'])
print(type(df['score']))

0    0.81
1    0.44
2     NaN
3    0.67
4    0.55
5    0.90
Name: score, dtype: float64
<class 'pandas.Series'>

### <u>***<div>DataFrame Filtering</div>***</u>

In [84]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, 28, 41, 52, 45, 72],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kalutara', 'Panadura', 'Gampaha'],
                   'score': [0.81, 0.44, 0.92, 0.62, 0.43, 0.95, 0.13]
                   })
print(df)
print()
filtered_df = df[df['age']>30]
print(filtered_df)

   age      city  score
0   22   Colombo   0.81
1   35     Kandy   0.44
2   28     Galle   0.92
3   41   Colombo   0.62
4   52  Kalutara   0.43
5   45  Panadura   0.95
6   72   Gampaha   0.13

   age      city  score
1   35     Kandy   0.44
3   41   Colombo   0.62
4   52  Kalutara   0.43
5   45  Panadura   0.95
6   72   Gampaha   0.13

In [94]:
import pandas as pd
df = pd.DataFrame({'age': [22, 35, 28, 41, 52, 45, 72],
                   'city': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kalutara', 'Panadura', 'Gampaha'],
                   'score': [0.81, 0.44, 0.92, 0.62, 0.43, 0.95, 0.13]
                   })
filtered_df = df[(df['city'] == 'Colombo') & (df['score'] > 0.5)]
print(filtered_df)

   age     city  score
0   22  Colombo   0.81
3   41  Colombo   0.62

Don't work <b style='color:yellow'>and , or</b> .Only work <b style='color:yellow'>& , |</b>

### <u>***<div>DataFrame NaN containing rows cleaning</div>***</u>

In [96]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
clean_df = df.dropna()
print(clean_df)

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
3  41.0  Colombo   0.67          1
5  33.0    Galle   0.90          1

In [101]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
print(df.isna())
print('---------------------------------')
print(df.isna().sum())

     age   city  score  purchased
0  False  False  False      False
1  False  False  False      False
2  False  False   True      False
3  False  False  False      False
4   True  False  False      False
5  False  False  False      False
---------------------------------
age          1
city         0
score        1
purchased    0
dtype: int64

We can fill <b style='color:green'>NaN</b> with <b style='color:green'>Mean,Meadian,Mode</b> with considering the data set.

### <u>***<div>DataFrame NaN containing column Filling</div>***</u>

In [123]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
age_mean = df['age'].mean()
score_median = df['score'].median()
# df['age'] , df['score'] = df['age'].fillna(age_mean) , df['score'].fillna(score_median)
df = df.fillna({'age':age_mean,'score':score_median})
print(df)

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle   0.67          1
3  41.0  Colombo   0.67          1
4  31.8    Kandy   0.55          0
5  33.0    Galle   0.90          1

In [132]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
df = df.dropna()
print(df)
df['age'] = df['age'].astype('int64')
print('----------------------------------')
print(df)
print('age dtype :',df['age'].dtype)

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
3  41.0  Colombo   0.67          1
5  33.0    Galle   0.90          1
----------------------------------
   age     city  score  purchased
0   22  Colombo   0.81          1
1   35    Kandy   0.44          0
3   41  Colombo   0.67          1
5   33    Galle   0.90          1
age dtype : int64

In [144]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
age_mean = df['age'].mean()
score_median = df['score'].median()
df = df.fillna({'age':age_mean,'score':score_median})
df['age']  = df['age'].astype('int32')
df = df.sort_values('score')
print(df)
print('---------------------------------')
df.sort_values('age',ascending=False)

   age     city  score  purchased
1   35    Kandy   0.44          0
4   31    Kandy   0.55          0
3   41  Colombo   0.67          1
2   28    Galle   0.67          1
0   22  Colombo   0.81          1
5   33    Galle   0.90          1
---------------------------------

   age     city  score  purchased
3   41  Colombo   0.67          1
1   35    Kandy   0.44          0
5   33    Galle   0.90          1
4   31    Kandy   0.55          0
2   28    Galle   0.67          1
0   22  Colombo   0.81          1

### <u>***<div>Adding Rows and Columns to DataFrame</div>***</u>

In [165]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
age_mean = df['age'].mean()
score_median = df['score'].median()
df = df.fillna({'age':age_mean,'score':score_median})
df['name'] = ['Kamal', 'Nimal', 'Kasun', 'Sunil', 'Saman', 'Bimal']
df.loc[len(df)] = [23, 'Matara', 0.73, 1, 'Susil']
print(df)

    age     city  score  purchased   name
0  22.0  Colombo   0.81          1  Kamal
1  35.0    Kandy   0.44          0  Nimal
2  28.0    Galle   0.67          1  Kasun
3  41.0  Colombo   0.67          1  Sunil
4  31.8    Kandy   0.55          0  Saman
5  33.0    Galle   0.90          1  Bimal
6  23.0   Matara   0.73          1  Susil

### <u>***<div>Getting Value counts from DataFrame</div>***</u>

In [168]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
print(df['city'].value_counts())
print(df['age'].value_counts())

city
Colombo    2
Kandy      2
Galle      2
Name: count, dtype: int64
age
22.0    1
35.0    1
28.0    1
41.0    1
33.0    1
Name: count, dtype: int64

### <u>***<div>DataFrame groupby() Command</div>***</u>

In [13]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
df = df.dropna()
print(df.groupby('city')['score'].mean())

city
Colombo    0.74
Galle      0.90
Kandy      0.44
Name: score, dtype: float64

In [27]:
import pandas as pd
df = pd.read_csv('customers_tiny.csv')
df = df.dropna()
new_df = df.groupby('city').agg(
    {'score': 'mean','age': 'mean'}
)
print(new_df)
print('--------------------')
df.groupby('city').agg(
    avg_score  = ('score', 'mean'),
    n_rows = ('score', 'count'),
    avg_age = ('age', 'mean'),
)

         score   age
city
Colombo   0.74  31.5
Galle     0.90  33.0
Kandy     0.44  35.0
--------------------

         avg_score  n_rows  avg_age
city
Colombo       0.74       2     31.5
Galle         0.90       1     33.0
Kandy         0.44       1     35.0

## **Probability & Statistics**

<img src='img2.png'>

<table style='margin:auto'>
<th style='color:purple;padding:15px;font-size:50px'>P(A) = n(A)/n(S)</th>
</table>

Q01. Consider a random experiment tossing a coin.For this random experiment,<br>
I.Write down the sample space.<br>
II.Event A is define as getting a head.Find the probability.

S = {T,H}<br>
A = {H}<br>
P(A) = 1/2 = 0.5

<img src='img3.png'>

Q02.For two event A and B,<br>
<b>P(AUB)=7/8 , P(AintersectB)=1/4 , P(A')=5/8</b><br>
Find P(B),

P(A) = 3/8 ; P(A) + P(B) = 9/8-2/8 = 5/8 ; P(B) = 3/4

<img src='img4.png'>

S = {HH,HT,TT,TH}<br>
A = {HH,HT}<br>
B = {TH,HH}<br>
AUB = {HH,HT,TH}<br>
A int. B = {HH}<br>
P(A)  = 0.5<br>
P(B) = 0.5<br>
P(AUB) = 0.75<br>
P(A int. B) = 0.5+0.5-0.75=0.25<br>
P(A int. B) = 0.5*0.5 = 0.25

<img src='img5.png'>

<img src='img6.png'>